version = 0.1
[default.deploy.parameters]
stack_name = "nueda-sqs-lambda"
resolve_s3 = true
s3_prefix = "nueda-sqs-lambda"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
