AWSTemplateFormatVersion: '2010-09-09'
Description: nueda-sqs-lambda - Processing an SQS message with a lambda
Transform: AWS::Serverless-2016-10-31


Resources:
  SimpleQueue:
    Type: AWS::SQS::Queue
  
  SQSPayloadLogger:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that logs the payload of messages sent to an associated SQS queue.
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Handler: src/handlers/sqs-payload-logger.sqsPayloadLoggerHandler
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SimpleQueue.Arn
      MemorySize: 128
      Timeout: 25 # Chosen to be less than the default SQS Visibility Timeout of 30 seconds
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaSQSQueueExecutionRole
