on:
  release:
    types: [published]

env:
  PIPELINE_USER_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  PIPELINE_USER_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: sam build
      - name: Run unit tests
        run: npm run unit-test
      - name: Integration tests
        run: npm run integration-test
      - name: Static analysis
        run: npm run static-analysis
  deploy-production:
    name: Deploy Production
    runs-on: ubuntu-latest
    needs: build
    environment: production
    steps:
      - name: Deploy
        run: sam deploy


