on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-deploy:
    name: Build and Deploy
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      - name: Build
        run: sam build
      - name: Run unit tests
        run: npm run unit-test
      - name: Integration tests
        run: npm run integration-test
      - name: Static analysis
        run: npm run static-analysis
      - name: Deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
      - name: Create Release Tag
        id: create-release-tag
        # left pads the run number with zeros to a length of 4; better alphabetical order
        run: echo "tag_name=r-$(printf %04d $GITHUB_RUN_NUMBER)" >> $GITHUB_OUTPUT
      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.create-release-tag.outputs.tag_name }}
          name: Release ${{ steps.create-release-tag.outputs.tag_name }}
          body: |
            ## Info
            Release creation to be reviewed. Please approve for production deployment
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


